name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7
      
      - name: Prepare Android Lime rebuild
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          set -euo pipefail
          haxelib setup ~/haxelib
          haxelib install hxpkg --quiet
          haxelib run hxpkg install
          rm -rf .haxelib/lime
          git clone https://github.com/FunkinCrew/lime .haxelib/lime/git
          git -C .haxelib/lime/git checkout 6421de16b9dfa4fb55c19f12db65d392a57585c8
          git -C .haxelib/lime/git submodule update --init --recursive --force
          haxelib dev lime .haxelib/lime/git
      
      - name: Setup Lime
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_21_arm64
          haxelib run lime config ANDROID_SETUP true
          
      - name: Rebuild Android Lime so
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          haxelib run lime rebuild android -release
          if [ ! -f .haxelib/lime/git/ndll/Android/liblime-64.so ]; then
            echo "ERROR: Missing Liblime 64 so"
            exit 1
          fi
      
      - name: Compile
        run: haxelib run lime build android -ONLY_ARM64
      
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: buildAndroid
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk